---
title: "Publications"
---

# Peer-Reviewed

- **Dye, K.**, Spence, C., & Brock, J. (2023). Reflections on the Infant Mental Health Endorsement® process in
Virginia. Infant Mental Health Journal. http://doi.org/10.1002/imhj.22058


- **Dye, K.** (2023). Relationships impacting special education teacher burnout. Kappa Delta Pi Record, 58(1).
https://doi-org.proxy.library.vcu.edu/10.1080/00228958.2022.2134949


-   **Dye, K.**, Wallace, M., Thompkins, K., Dawes, S. (2022). An urban partnership: Embracing collaboration and feedback. *Journal of Community Engagement and Scholarship*, 14(2). https://jces.ua.edu/articles/10.54656/jces.v14i2.38


# Accepted for Publication

-   **Dye, K.**, & Walker Bowman, R.W. (in press- will publish in Fall 2023). Leadership matters: Self-contained special educators' perceptions of administrator support. *Journal of the American Academy of Special Education Professionals*.


# Other Publications

-   Becker, J., Robnolt, V., **Dye, K.**, & Ross, E. (2021). *Will they stay or will they go? Analysis of the VDOE working conditions survey*. Richmond, VA: Metropolitan Educational Research Consortium. [ https://merc.soe.vcu.edu/reports/published-reports/will-they-stay/](https://merc.soe.vcu.edu/reports/published-reports/will-they-stay/)
